include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ✅ CRITICAL: Prevent bugs we just fixed
    avoid_dynamic_calls: true
    prefer_const_constructors: true
    always_use_package_imports: true
    
    # ✅ State management safety
    use_build_context_synchronously: true
    
    # ✅ Null safety
    prefer_null_aware_operators: true
    avoid_returning_null_for_void: true
    
    # ✅ Code quality
    prefer_final_locals: true
    unnecessary_null_checks: true
    avoid_print: true

analyzer:
  errors:
    # ✅ Make these errors (not warnings)
    avoid_dynamic_calls: error
    use_build_context_synchronously: error
    invalid_annotation_target: ignore
