include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ✅ CRITICAL: Prevent bugs we just fixed
    avoid_dynamic_calls: true
    prefer_const_constructors: true
    always_use_package_imports: true
    curly_braces_in_flow_control_structures: true

    # ✅ State management safety
    use_build_context_synchronously: true

    # ✅ Null safety & Type safety
    prefer_null_aware_operators: true
    avoid_returning_null_for_void: true
    avoid_null_checks_in_equality_operators: true
    unnecessary_null_checks: true
    avoid_type_to_string: true
    prefer_typing_uninitialized_variables: true

    # ✅ Error handling
    only_throw_errors: true
    use_rethrow_when_possible: true
    avoid_catching_errors: true

    # ✅ Code quality & Performance
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

    # ✅ Resource management
    close_sinks: true
    cancel_subscriptions: true

analyzer:
  errors:
    # ✅ Make these errors (not warnings) - BLOCK builds!
    avoid_dynamic_calls: error
    use_build_context_synchronously: error
    avoid_catching_errors: error
    only_throw_errors: error
    close_sinks: error
    cancel_subscriptions: error

    # ✅ Ignore specific warnings
    invalid_annotation_target: ignore

    # ✅ Allow print in tests for debugging
    avoid_print: ignore
